import gradio as gr
from PIL import Image
import torch
import re
from src.detector import HallucinationDetector

# Initialize the detector globally
print("Initializing models. This may take a moment...")
detector = HallucinationDetector()

def analyze_ui(image, candidate_caption, threshold):
    if image is None or not candidate_caption.strip():
        return "Please provide both an image and a candidate caption.", "", "", "<p>No input provided.</p>"
        
    try:
        results = detector.analyze_hallucination(
            image=image, 
            candidate_caption=candidate_caption, 
            global_threshold=threshold
        )
        
        # Format the output
        is_hal = results["is_hallucination"]
        verdict = "🚨 Hallucination Detected!" if is_hal else "✅ Consistent (No Hallucination)"
        
        global_sim = f"{results['global_similarity']:.4f} (Threshold: {results['global_threshold']})"
        ref_caption = results["reference_caption"]
        
        suspicious = ", ".join(results["suspicious_words"]) if results["suspicious_words"] else "None detected."
        
        # Create highlighted text for explanation
        highlighted_text = candidate_caption
        for word in results["suspicious_words"]:
            # Wrap suspicious words in HTML for highlighting
            highlighted_text = re.sub(
                rf'\b({re.escape(word)})\b', 
                r'<span style="background-color: #ffcccc; color: #cc0000; padding: 2px 4px; border-radius: 4px; font-weight: bold;">\1</span>', 
                highlighted_text, 
                flags=re.IGNORECASE
            )
            
        explanation = f"<h3>Token-Level Analysis</h3>"
        explanation += f"<div style='padding: 15px; border: 1px solid #ddd; border-radius: 8px; background-color: #f9f9f9;'>"
        explanation += f"<p style='font-size: 16px; line-height: 1.6;'>{highlighted_text}</p>"
        explanation += f"</div><br>"
        
        if results["suspicious_words"]:
            explanation += f"<p><strong>Suspicious Tokens:</strong> {suspicious}</p>"
            explanation += f"<p style='color: #666; font-size: 14px;'><em>*These tokens have low visual grounding in the image, suggesting they might be fabricated by the language model.</em></p>"
        else:
            explanation += "<p style='color: green;'>All meaningful tokens appear to be visually grounded.</p>"
            
        return verdict, global_sim, ref_caption, explanation
        
    except Exception as e:
        return f"Error: {str(e)}", "", "", f"<p>Error details: {str(e)}</p>"

# Build Gradio Interface
with gr.Blocks(title="MLLM Hallucination Detector", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🔍 MLLM Hallucination Detector")
    gr.Markdown("### Detect inconsistencies between images and generated captions using Vision-Language Models.")
    gr.Markdown("This research prototype uses **CLIP** for cross-modal consistency scoring and token-level attribution, and **BLIP** for generative cross-validation.")
    
    with gr.Row():
        with gr.Column(scale=1):
            input_image = gr.Image(type="pil", label="Upload Image")
            input_caption = gr.Textbox(lines=3, label="Candidate Caption (Generated by an MLLM)")
            threshold_slider = gr.Slider(minimum=0.1, maximum=0.4, value=0.24, step=0.01, label="Detection Threshold (Cosine Similarity)")
            analyze_btn = gr.Button("Analyze for Hallucinations", variant="primary")
            
        with gr.Column(scale=1):
            verdict_out = gr.Textbox(label="Verdict")
            score_out = gr.Textbox(label="Global Similarity Score")
            ref_out = gr.Textbox(label="Reference Caption (BLIP Ground Truth)")
            explanation_out = gr.HTML(label="Explainability (Interpretability)")
            
    analyze_btn.click(
        fn=analyze_ui,
        inputs=[input_image, input_caption, threshold_slider],
        outputs=[verdict_out, score_out, ref_out, explanation_out]
    )
    
    gr.Markdown("---")
    gr.Markdown("""
    **Research Context & Trustworthy AI**
    
    Hallucinations in Multimodal Large Language Models (MLLMs) occur when the text generation module produces entities or attributes that are ungrounded in the visual input. Mitigating this is a core challenge in Trustworthy AI.
    
    This system implements a two-fold approach:
    1. **Discriminative Verification:** Uses CLIP's aligned vision-language embedding space to compute a global grounding score.
    2. **Explainable Attribution:** Projects individual tokens into the joint space to pinpoint the exact locus of the hallucination, offering interpretability rather than a black-box binary classification.
    """)

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=7860)
